# based on https://jekyllrb.com/docs/continuous-integration/travis-ci/
sudo: false
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler
