name: Deposit new posts on Zenodo

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deposit:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
             python3-pip libcurl4-openssl-dev xfonts-base xfonts-75dpi xvfb qt5-default xkb-data x11-xkb-utils \
             ruby-full build-essential zlib1g-dev
            
            wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
            sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb

            pip3 install --user --upgrade pip
            pip3 install --user requests
            pip3 install --user coloredlogs
      - name: Install Jekyll
        run: gem install jekyll bundler
            
      - name: Build page
        run: bundle exec jekyll build

      - name: Capture page as PDF
        run: |
            export DISPLAY=localhost:1.0
            export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
            xvfb-run make update_zenodo_deposit
